version: '3'

services:
  nginx:
    container_name: "nginx"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www/
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - php
  php:
    image: php:8.2-fpm
    container_name: "php"
    volumes:
      - ./:/var/www/