version: '3'

services:
  nginx:
    container_name: "nginx"
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www/
    ports:
      - "443:443"
      - "80:80"
  php:
    image: php:8.2-fpm
    volumes:
      - ./:/var/www/