networks:
  ionium_network:
    name: ionium_network
services:
  nginx_service:
    container_name: nginx_container
    build:
      context: /var/www/docker/images/nginx
      tags:
        - nginx125:1.0
    ports:
      - 80:80
    volumes:
      - /var/www/docker/configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/www:/var/www/public_html
    networks:
      - ionium_network
    depends_on:
      - php_service
      - mysql_service 
  php_service:
    container_name: php_container
    build: /var/www/docker/images/php
    volumes:
      - ./www:/var/www
    networks:
      - ionium_network
    depends_on:
      - mysql_service
  mysql_service:
    container_name: mysql_container
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - ionium_network     
  phpmyadmin_service:
    container_name: phpmyadmin_container
    image: phpmyadmin
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql_container
    networks:
      - ionium_network
    depends_on:
      - mysql_service
