networks:
  frontend:
  backend:
services:
  # nginx proxy service (based on nginx official image) to act as a web server and proxy server
  proxy:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/ionium.ru
      - ./nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend
  # php-fpm service (based on php official image) to process our php code
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: laravelgis-php:latest
    # map the current directory to /var/www/app in the container (the same as for the proxy service)
    volumes:
      - ./:/var/www/ionium.ru
    networks:
      - backend